
// get our lib config vars
const config = require("./config");

/** Piece class for CheSSsk
 * 
 * Author: Shane Koehler
 */
class Piece
{
    /**
     * 
     * @param {string} t 
     * @param {string} c 
     * @param {string} arg 
     */
    constructor(t, c, arg)
    {
        // assign vars
        this.type = t.toUpperCase();
        this.color = c.toUpperCase();
        this.hasMoved = false;

        // we have an actual ID submitted, set and return
        if ( arg.match(config.PREG_ID) )
        {
            this._id = arg;
            return;
        }

        // generates unique id for this piece
        // concatenating the color, type, and original board location (ie b2)
        // example: WKe1
        this._id = this.color + this.type + arg;
    }

    /** getID
     * simply returns our unique id generated by constructor
     */
    getID()
    {
        return this._id;
    }

}

module.exports = Piece;